In [55]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv("C:\\program1\\class\\car.data",header=None)
df.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df

      vhigh.1      2   2.1  small   low  unacc
vhigh
vhigh   vhigh      2     2  small   med  unacc
vhigh   vhigh      2     2  small  high  unacc
vhigh   vhigh      2     2    med   low  unacc
vhigh   vhigh      2     2    med   med  unacc
vhigh   vhigh      2     2    med  high  unacc
...       ...    ...   ...    ...   ...    ...
low       low  5more  more    med   med   good
low       low  5more  more    med  high  vgood
low       low  5more  more    big   low  unacc
low       low  5more  more    big   med   good
low       low  5more  more    big  high  vgood

[1727 rows x 6 columns]

In [ ]:
df.columns

In [56]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
# LabelEncoder 객체 생성
label = LabelEncoder()

#LabelEncoder를 적용하여 변환
df['class'] = label.fit_transform(df['class'])
df['buying'] = label.fit_transform(df['buying'])
df['maint'] = label.fit_transform(df['maint'])
df['doors'] = label.fit_transform(df['doors'])
df['persons'] = label.fit_transform(df['persons'])
df['lug_boot'] = label.fit_transform(df['lug_boot'])
df['safety'] = label.fit_transform(df['safety'])

df

       vhigh.1  2  2.1  small  low  unacc
vhigh
vhigh        3  0    0      2    2  unacc
vhigh        3  0    0      2    0  unacc
vhigh        3  0    0      1    1  unacc
vhigh        3  0    0      1    2  unacc
vhigh        3  0    0      1    0  unacc
...        ... ..  ...    ...  ...    ...
low          1  3    2      1    2   good
low          1  3    2      1    0  vgood
low          1  3    2      0    1  unacc
low          1  3    2      0    2   good
low          1  3    2      0    0  vgood

[1727 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# 특정 열들을 선택하여 스케일링 적용
columns_to_scale = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

# 스케일링 후 데이터 확인
df

In [61]:
# 컬렴명 확인
df.columns

Index(['vhigh.1', '2', '2.1', 'small', 'low', 'unacc'], dtype='object')

In [ ]:
# 레이블 갯수 확인 (그래프)
sns.countplot(data = df, x="class")
plt.xlabel("Car")
plt.ylabel("Count")
plt.title("Class")

In [62]:
# 결측치 확인
df.isnull().sum()

vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

In [63]:
# 결측치 제거
df = df.dropna()
df.isnull().sum()

vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

In [ ]:
X=df.drop('class', axis=1)
# class 컬럼 삭제하여 X에 저장, axis=1 이면 y축 기준
X.head()
# head()는 첫 5행만 출력함

In [ ]:
y=df['class']
y.value_counts()

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
# random_state는 데이터를 무작위로 나누거나 섞을 때 사용되는 난수 발생기의 시드(seed) 값
X_train

In [ ]:
X_train.columns

In [ ]:
#X_train의 특성 개수
X_train.shape[1]

In [ ]:
y_train

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test) 
#예측한 값을 pred_lr에 저장

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
#예측한 값과 실제 값을 비교
print (confusion_matrix(y_test, pred_lr))